### ISSUE TITLE
little fix.

### ISSUE THREAD

**Issue by hitrpr** [schroef/copy-blender-info#1]
Please change string 53, to block autolinking on the hash (at developer.blender.org): with such quotes `hash` will not produce autolink
```
		appInfo = version+", `"+buildHash.decode()+"`, "+comDate.decode()+" "+comTime.decode()
```

**Comment by schroef** [comment]
Well my addon was just an idea back then. It was before Blender added their own bug report method. I posted my addon at a lot places a short while after we got a much better version.

You do know of the bug report button in the file menu, do you?

**Comment by schroef** [comment]
Below you can see where it is, it copies all the info automatically
![dat-copied-report-bug-button](https://user-images.githubusercontent.com/6923008/163039472-cbbabcc5-e07b-430f-a8ce-c1de00e5e1c0.png)
![report-bug-button](https://user-images.githubusercontent.com/6923008/163039476-61506fb2-fb6f-4b07-91ff-9e2809e5c1b2.png)

**Comment by hitrpr** [comment]
Yep, I know about it. Also, I believe, we discuss it, and you made it, then devs grab the idea and made it built in.

But I am using a part of your addon as additional tool: sometimes I need just to copy info to buffer, without sending report directly. Nevermind. I will add options and publish it with reference to you.

**Comment by schroef** [comment]
Ah i see, your free todo so, you can also make a pull request of course

**Comment by schroef** [comment]
Using you code i know see this; ```2.83.0, `211b6c29f771`, 2020-06-03 14:38```
it adds single quotes, why is that needed?

EDIT
I see now, blender uses this as well. Ill adjust it
![Screen Shot 2022-04-19 at 11 56 24](https://user-images.githubusercontent.com/6923008/164045608-42b9e115-c674-4bf6-8c6d-d760766bfe3f.png)

But i dont see it being linked, it gets highlighed. I checked some bug reports
![Screen Shot 2022-04-19 at 11 58 06](https://user-images.githubusercontent.com/6923008/164045929-36b1a1cd-8287-4906-a9b0-283da37e8dd7.png)

it looks the same as when using ``` THIS IS SOME TEXT ``` with markdown, using ```

**Comment by hitrpr** [comment]
yup, blender use it to separate version hashes without link and hashes with links to tickets.
quotes just a markdown of raw code string

**Comment by schroef** [comment]
I thought you wanted a working link, but its i added it in.
We could add more info, perhaps its handy?

**Comment by hitrpr** [comment]
nope, i wanted to avoid link, because it is wrong link, it takes blender`s has and links to task, that have same hash
